### ISSUE TITLE
npm install creates errors - I am using node v16.7.0

### ISSUE THREAD

**Issue by AgedLace** [broeker/spacebook#32]
**Describe the bug**
I cloned the repo locally then typed "npm install" as stated in the directions.  

**To Reproduce**
This is the ERR output from my debug.log file ...
-----
3863 info run sharp@0.26.3 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
3864 info run sharp@0.25.4 install node_modules/eleventy-plugin-lazyimages/node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
3865 info run sharp@0.26.3 install { code: 0, signal: null }
3866 timing build:run:install:node_modules/sharp Completed in 1138ms
3867 info run sharp@0.25.4 install { code: 1, signal: null }
3868 timing reify:rollback:createSparse Completed in 1170ms
3869 timing reify:rollback:retireShallow Completed in 0ms
3870 timing command:install Completed in 12061ms
3871 verbose stack Error: command failed
3871 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
3871 verbose stack     at ChildProcess.emit (node:events:394:28)
3871 verbose stack     at maybeClose (node:internal/child_process:1064:16)
3871 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
3872 verbose pkgid sharp@0.25.4
3873 verbose cwd /home/deb/VMShares/My Projects/Documentation Site Generators/spacebook
3874 verbose Linux 5.13.12-1-MANJARO
3875 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "core-js@3.17.2"
3876 verbose node v16.7.0
3877 verbose npm  v7.21.0
3878 error code 1
3879 error path /home/deb/VMShares/My Projects/Documentation Site Generators/spacebook/node_modules/eleventy-plugin-lazyimages/node_modules/sharp
3880 error command failed
3881 error command sh -c (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
3882 error make: Entering directory '/home/deb/VMShares/My Projects/Documentation Site Generators/spacebook/node_modules/eleventy-plugin-lazyimages/node_modules/sharp/build'
3882 error   CC(target) Release/obj.target/nothing/../../../node-addon-api/nothing.o
3882 error   AR(target) Release/obj.target/../../../node-addon-api/nothing.a
3882 error   COPY Release/nothing.a
3882 error   TOUCH Release/obj.target/libvips-cpp.stamp
3882 error   CXX(target) Release/obj.target/sharp/src/common.o
3882 error make: Leaving directory '/home/deb/VMShares/My Projects/Documentation Site Generators/spacebook/node_modules/eleventy-plugin-lazyimages/node_modules/sharp/build'
3883 error info sharp Using cached /home/deb/.npm/_libvips/libvips-8.9.1-linux-x64.tar.gz
3883 error gyp info it worked if it ends with ok
3883 error gyp info using node-gyp@8.1.0
3883 error gyp info using node@16.7.0 | linux | x64
3883 error gyp info find Python using Python version 3.9.6 found at "/usr/bin/python3"
3883 error (node:36175) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
3883 error (Use `node --trace-deprecation ...` to show where the warning was created)
3883 error gyp info spawn /usr/bin/python3
3883 error gyp info spawn args [
3883 error gyp info spawn args   '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
3883 error gyp info spawn args   'binding.gyp',
3883 error gyp info spawn args   '-f',
3883 error gyp info spawn args   'make',
3883 error gyp info spawn args   '-I',
3883 error gyp info spawn args   '/home/deb/VMShares/My Projects/Documentation Site Generators/spacebook/node_modules/eleventy-plugin-lazyimages/node_modules/sharp/build/config.gypi',
3883 error gyp info spawn args   '-I',
3883 error gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
3883 error gyp info spawn args   '-I',
3883 error gyp info spawn args   '/home/deb/.cache/node-gyp/16.7.0/include/node/common.gypi',
3883 error gyp info spawn args   '-Dlibrary=shared_library',
3883 error gyp info spawn args   '-Dvisibility=default',
3883 error gyp info spawn args   '-Dnode_root_dir=/home/deb/.cache/node-gyp/16.7.0',
3883 error gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
3883 error gyp info spawn args   '-Dnode_lib_file=/home/deb/.cache/node-gyp/16.7.0/<(target_arch)/node.lib',
3883 error gyp info spawn args   '-Dmodule_root_dir=/home/deb/VMShares/My Projects/Documentation Site Generators/spacebook/node_modules/eleventy-plugin-lazyimages/node_modules/sharp',
3883 error gyp info spawn args   '-Dnode_engine=v8',
3883 error gyp info spawn args   '--depth=.',
3883 error gyp info spawn args   '--no-parallel',
3883 error gyp info spawn args   '--generator-output',
3883 error gyp info spawn args   'build',
3883 error gyp info spawn args   '-Goutput_dir=.'
3883 error gyp info spawn args ]
3883 error gyp info spawn make
3883 error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
3883 error <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
3883 error <command-line>: note: this is the location of the previous definition
3883 error ../src/common.cc:22:10: fatal error: napi.h: No such file or directory
3883 error    22 | #include <napi.h>
3883 error       |          ^~~~~~~~
3883 error compilation terminated.
3883 error make: *** [sharp.target.mk:137: Release/obj.target/sharp/src/common.o] Error 1
3883 error gyp ERR! build error
3883 error gyp ERR! stack Error: `make` failed with exit code: 2
3883 error gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
3883 error gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
3883 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
3883 error gyp ERR! System Linux 5.13.12-1-MANJARO
3883 error gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
3883 error gyp ERR! cwd /home/deb/VMShares/My Projects/Documentation Site Generators/spacebook/node_modules/eleventy-plugin-lazyimages/node_modules/sharp
3883 error gyp ERR! node -v v16.7.0
3883 error gyp ERR! node-gyp -v v8.1.0
3883 error gyp ERR! not ok
3884 verbose exit 1

**Expected behavior**
I was expecting spacebook to install correctly.

Thank you.

**Comment by AgedLace** [comment]
Since I'm unable to get Spacebook to work, I have found another means of doing what I needed to do.
